package data_generation;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;
public class AgentInfo {

    int id_person;
    double wp;
    int tripnum;
    int starttime;
    int endtime;
    int TAZ;
    double h_x;
    double h_y;
    double s_x;
    double s_y;
    double d_x;
    double d_y;
    int bike;
    int age;
    int gender;
    int license;
    int tickets;
    int modechoice;
    int caravailability;
    int mobtools;
    double inc1000;
    int day;
    int tripmode;
    int trippurpose;
    double tripdistance;
    double tripduration;
    int id_tour;
}
